# Build settings

markdown: kramdown
permalink: pretty

avatar: avatar.jpg
blurb: <strong>But I must explain to you how all this mistaken idea of denouncing pleasure</strong> and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness.
No one rejects, dislikes, or avoids pleasure itself, because it is pleasure, but because those who do not know how to pursue pleasure rationally encounter consequences that are extremely painful.

port: 8000

sass:
    sass_dir: _sass
sass:
  sass_dir: /assets/css/
  style: :nested
