#Portfolio settings
title: anton_kann
description: software development // web design // translation services
email: anton.kann@gmail.com

#Menu item list
menu:
  - {name: About Me, url: '#about-me'}
  - {name: Work, url: '#work'}
  - {name: Clients, url: '#clients'}
  - {name: Contact, url: '#contact'}


# SEO Section

# NOTE: Providing SEO information will make this website more searchable on the internet.



# About Section
blurb: <strong>But I must explain to you how all this mistaken idea of denouncing pleasure</strong> and praising pain was born and I will give you a complete account of the system, and expound the actual teachings of the great explorer of the truth, the master-builder of human happiness.

skills:
  - {name: Front-End Development, level: '8'}
  - {name: Back-End Development, level: '5'}
  - {name: UX Design, level: '7'}
  - {name: Testing, level: '5'}

avatar: 'avatar.jpg'
